[api]
service_token_test = 'ext_token_d286323ed20582eb5584be1b35ca86cd'
service_token_prod = 'ext_token_df2b2f6fae1808504688f152dc8a45be'
[auth]
token = 'AnimalEye2025@'
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "dracic@animal-eye-iowa.com"
sender_password = "bnja nxhi qpdm thkx"
recipient_email = "animaleyeiowa@gmail.com"
[url]
catalogue_url = "http://pro4eyes.com/api/external_catalogues.php"
patient_add_url = "http://pro4eyes.com/api/external_patient_add.php"